/*

 GUI_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Imanol Barriuso\Documents\Repositorios\red_hot_princess_carnage\res\tiles\sprite_bkg_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

unsigned const char gui_map[] =
{
  0xC0,0xC1,0xC1,0xC1,0xC1,0xC0,0xC0,0xC0,0xC0,0xC0,
  0xC0,0xC0,0xC0,0xC0,0xC0,0xC0,0xC4,0xC4,0xC4,0xC0
};

/* End of GUI_MAP.C */
