/*

 LEVEL0_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\Imanolea\Documents\GitHub\bitbitjam3_red_hot_princess_carnage\res\tiles\bkg_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level0_mapWidth 32
#define level0_mapHeight 32
#define level0_mapBank 2

extern unsigned char level0_map[];

/* End of LEVEL0_MAP.H */
