/*

 STORY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 32 x 32
   Tile set      : D:\Users\Imanol\Documents\GitHub\bitbitjam3_red_hot_princess_carnage\res\tiles\story_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define story_mapWidth 32
#define story_mapHeight 32
#define story_mapBank 2

extern unsigned char story_map[];

/* End of STORY_MAP.H */
