/*

 SPRITE_BKG_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sprite_bkg_tilesetBank 1
/* Start of tile array. */
extern unsigned char sprite_bkg_tileset[];

/* End of SPRITE_BKG_TILESET.H */
